// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Expensify.Modules.Users.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class AddUserPreferences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "currency",
                schema: "users",
                table: "users",
                type: "character varying(3)",
                maxLength: 3,
                nullable: false,
                defaultValue: "GBP");

            migrationBuilder.AddColumn<int>(
                name: "month_start_day",
                schema: "users",
                table: "users",
                type: "integer",
                nullable: false,
                defaultValue: 1);

            migrationBuilder.AddColumn<string>(
                name: "timezone",
                schema: "users",
                table: "users",
                type: "character varying(100)",
                maxLength: 100,
                nullable: false,
                defaultValue: "UTC");

            migrationBuilder.AddCheckConstraint(
                name: "ck_users_month_start_day",
                schema: "users",
                table: "users",
                sql: "month_start_day >= 1 AND month_start_day <= 28");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropCheckConstraint(
                name: "ck_users_month_start_day",
                schema: "users",
                table: "users");

            migrationBuilder.DropColumn(
                name: "currency",
                schema: "users",
                table: "users");

            migrationBuilder.DropColumn(
                name: "month_start_day",
                schema: "users",
                table: "users");

            migrationBuilder.DropColumn(
                name: "timezone",
                schema: "users",
                table: "users");
        }
    }
}

